/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Briefs */
        get: operations["briefs_api_briefs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefs/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brief */
        get: operations["brief_api_briefs__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Order */
        post: operations["new_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description What an order would cost, using the SAME model the fills use -- so the ticket's
         *     estimate is not a different number from what actually gets booked.
         */
        post: operations["preview_api_orders_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{oid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Order */
        delete: operations["delete_order_api_orders__oid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Picks */
        get: operations["picks_api_picks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolios */
        get: operations["portfolios_api_portfolios_get"];
        put?: never;
        /** New Portfolio */
        post: operations["new_portfolio_api_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_api_portfolios__pid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Search */
        get: operations["stock_search_api_stocks_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock */
        get: operations["stock_api_stocks__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{symbol}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bars */
        get: operations["bars_api_stocks__symbol__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategies */
        get: operations["strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategy */
        get: operations["strategy_api_strategies__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{slug}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Take a gated candidate live. Refuses anything that has not passed the gate.
         */
        post: operations["approve_api_strategies__slug__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{slug}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retire
         * @description Take a strategy out of service. Requires explicit confirmation.
         */
        post: operations["retire_api_strategies__slug__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{tid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Journal */
        patch: operations["journal_api_trades__tid__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Bar */
        Bar: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Time */
            time: string;
            /** Volume */
            volume: number;
        };
        /** Brief */
        Brief: {
            /** Conflicts */
            conflicts: string[];
            /** Date */
            date: string;
            /** Generatedat */
            generatedAt: string | null;
            /** Notablepicks */
            notablePicks: {
                [key: string]: string;
            }[];
            /** Overview */
            overview: string;
            /** Pending */
            pending: boolean;
            /** Positionnotes */
            positionNotes: {
                [key: string]: string;
            }[];
        };
        /** BriefListItem */
        BriefListItem: {
            /** Date */
            date: string;
            /** Pending */
            pending: boolean;
        };
        /** CostPreview */
        CostPreview: {
            /** Chargebreakdown */
            chargeBreakdown: {
                [key: string]: number;
            };
            /** Charges */
            charges: number;
            /** Dpcharge */
            dpCharge: number;
            /** Estprice */
            estPrice: number;
            /** Note */
            note: string;
            /** Price */
            price: number;
            /** Slippagebps */
            slippageBps: number;
            /** Total */
            total: number;
            /** Value */
            value: number;
        };
        /** DelayedFeed */
        DelayedFeed: {
            /** Lagminutes */
            lagMinutes: number;
            /** Stale */
            stale: boolean;
        };
        /** DemoteRequest */
        DemoteRequest: {
            /** Confirm */
            confirm: boolean;
            /** Reason */
            reason: string;
        };
        /** FlaggedBy */
        FlaggedBy: {
            /** Horizon */
            horizon: string;
            /** Signaldate */
            signalDate: string;
            /** Status */
            status: string;
            /** Strategy */
            strategy: string;
            /** Strategyid */
            strategyId: string;
        };
        /** Fundamentals */
        Fundamentals: {
            /** Approx */
            approx: boolean;
            /** Asof */
            asOf: string;
            /** Deratio */
            deRatio: number | null;
            /** Epsttm */
            epsTtm: number | null;
            /** Note */
            note: string;
            /** Profitcagr3 */
            profitCagr3: number | null;
            /** Roce */
            roce: number | null;
            /** Salescagr3 */
            salesCagr3: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JournalUpdate */
        JournalUpdate: {
            /** Note */
            note: string;
        };
        /** NewOrder */
        NewOrder: {
            /** Bracketstop */
            bracketStop?: number | string | null;
            /** Brackettarget */
            bracketTarget?: number | string | null;
            /** Journalnote */
            journalNote?: string | null;
            /** Limitprice */
            limitPrice?: number | string | null;
            /** Pickid */
            pickId?: number | null;
            /** Portfolioid */
            portfolioId: number;
            /** Qty */
            qty: number;
            /** Side */
            side: string;
            /** Symbol */
            symbol: string;
            /** Triggerprice */
            triggerPrice?: number | string | null;
            /** Type */
            type: string;
        };
        /** NewPortfolio */
        NewPortfolio: {
            /** Name */
            name: string;
            /** Startcapital */
            startCapital: number | string;
        };
        /** OrderOut */
        OrderOut: {
            /** Bracketstop */
            bracketStop: number | null;
            /** Brackettarget */
            bracketTarget: number | null;
            /** Created */
            created: string;
            /** Id */
            id: number;
            /** Journalnote */
            journalNote: string | null;
            /** Parentorderid */
            parentOrderId: number | null;
            /** Price */
            price: number | null;
            /** Qty */
            qty: number;
            /** Side */
            side: string;
            /** Status */
            status: string;
            /** Statusnote */
            statusNote: string | null;
            /** Symbol */
            symbol: string;
            /** Type */
            type: string;
        };
        /** Pick */
        Pick: {
            /** Approx */
            approx: boolean;
            /** Btcagr */
            btCagr: number | null;
            /** Btwinrate */
            btWinRate: number | null;
            /** Company */
            company: string;
            /** Conflict */
            conflict: string | null;
            /** Exch */
            exch: string;
            /** Hitrate */
            hitRate: number | null;
            /** Holddays */
            holdDays: number;
            /** Horizon */
            horizon: string;
            /** Id */
            id: number;
            /** Livereturn */
            liveReturn: number | null;
            /** Pickreturn */
            pickReturn: number | null;
            /** Reason */
            reason: string;
            /** Ref */
            ref: number;
            /** Score */
            score: number;
            /** Sector */
            sector: string | null;
            /** Signaldate */
            signalDate: string;
            /** Status */
            status: string;
            /** Stop */
            stop: number | null;
            /** Strategy */
            strategy: string;
            /** Strategyid */
            strategyId: string;
            /** Symbol */
            symbol: string;
            /** Target */
            target: number | null;
            /** Window */
            window: string;
        };
        /** PortfolioDetail */
        PortfolioDetail: {
            /** Asof */
            asOf: string | null;
            /** Cash */
            cash: number;
            /** Charges */
            charges: number;
            /** Currentvalue */
            currentValue: number;
            /** Curve */
            curve: number[];
            /** Curvedates */
            curveDates: string[];
            /** Id */
            id: number;
            /** Invested */
            invested: number;
            /** Maxdd */
            maxDd: number | null;
            /** Name */
            name: string;
            /** Niftycurve */
            niftyCurve: number[];
            /** Niftyreturnpct */
            niftyReturnPct: number | null;
            /** Orders */
            orders: components["schemas"]["OrderOut"][];
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /** Realisedpnl */
            realisedPnl: number;
            /** Returnpct */
            returnPct: number;
            /** Startcapital */
            startCapital: number;
            /** Trades */
            trades: components["schemas"]["TradeOut"][];
            /** Unrealisedpnl */
            unrealisedPnl: number;
            /** Winrate */
            winRate: number | null;
            /** Xirr */
            xirr: number | null;
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Asof */
            asOf: string | null;
            /** Cash */
            cash: number;
            /** Charges */
            charges: number;
            /** Currentvalue */
            currentValue: number;
            /** Id */
            id: number;
            /** Invested */
            invested: number;
            /** Maxdd */
            maxDd: number | null;
            /** Name */
            name: string;
            /** Niftyreturnpct */
            niftyReturnPct: number | null;
            /** Realisedpnl */
            realisedPnl: number;
            /** Returnpct */
            returnPct: number;
            /** Startcapital */
            startCapital: number;
            /** Unrealisedpnl */
            unrealisedPnl: number;
            /** Winrate */
            winRate: number | null;
            /** Xirr */
            xirr: number | null;
        };
        /** PositionOut */
        PositionOut: {
            /** Avg */
            avg: number;
            /** Days */
            days: number;
            /** Ltp */
            ltp: number | null;
            /** Pnl */
            pnl: number | null;
            /** Pnlpct */
            pnlPct: number | null;
            /** Qty */
            qty: number;
            /** Symbol */
            symbol: string;
        };
        /** PreviewRequest */
        PreviewRequest: {
            /** Price */
            price: number | string;
            /** Qty */
            qty: number;
            /** Side */
            side: string;
            /** Symbol */
            symbol: string;
        };
        /** StaleWarning */
        StaleWarning: {
            /** Job */
            job: string;
            /** Message */
            message: string;
            /** Since */
            since: string | null;
        };
        /** Status */
        Status: {
            /** Dataasof */
            dataAsOf: string | null;
            delayedFeed: components["schemas"]["DelayedFeed"] | null;
            /** Marketlabel */
            marketLabel: string;
            /** Marketopen */
            marketOpen: boolean;
            /** Nowist */
            nowIst: string;
            staleWarning: components["schemas"]["StaleWarning"] | null;
        };
        /** StockDetail */
        StockDetail: {
            /** Changepct */
            changePct: number | null;
            /** Company */
            company: string;
            /** Exch */
            exch: string;
            /** Flaggedby */
            flaggedBy: components["schemas"]["FlaggedBy"][];
            fundamentals: components["schemas"]["Fundamentals"] | null;
            /** Isin */
            isin: string;
            /** Lastclose */
            lastClose: number | null;
            /** Lastdate */
            lastDate: string | null;
            /** Symbol */
            symbol: string;
            /** Tvsymbol */
            tvSymbol: string;
        };
        /** StockHit */
        StockHit: {
            /** Company */
            company: string;
            /** Exch */
            exch: string;
            /** Isin */
            isin: string;
            /** Symbol */
            symbol: string;
        };
        /** StrategyDetail */
        StrategyDetail: {
            /** Approx */
            approx: boolean;
            /** Approxreasons */
            approxReasons: string[];
            /** Avghold */
            avgHold: number | null;
            /** Btcagr */
            btCagr: number | null;
            /** Curvedates */
            curveDates: string[];
            /** Equitycurve */
            equityCurve: number[];
            /** Gateverdict */
            gateVerdict: string | null;
            /** Hitrate */
            hitRate: number | null;
            /** Horizon */
            horizon: string;
            /** Id */
            id: string;
            /** Liveclosed */
            liveClosed: number;
            /** Livereturn */
            liveReturn: number | null;
            /** Maxdd */
            maxDd: number | null;
            /** Name */
            name: string;
            /** Niftycurve */
            niftyCurve: number[];
            /** Notes */
            notes: string;
            /** Origin */
            origin: string;
            /** Rules */
            rules: string[];
            /** Sharpe */
            sharpe: number | null;
            /** Status */
            status: string;
            /** Statusreason */
            statusReason: string | null;
            /** Tradelist */
            tradeList: components["schemas"]["TradeRow"][];
            /** Tradelistsource */
            tradeListSource: string;
            /** Trades */
            trades: number;
            /** Walkforward */
            walkForward: components["schemas"]["WalkForwardWindow"][];
            /** Winrate */
            winRate: number | null;
        };
        /** StrategySummary */
        StrategySummary: {
            /** Approx */
            approx: boolean;
            /** Avghold */
            avgHold: number | null;
            /** Btcagr */
            btCagr: number | null;
            /** Gateverdict */
            gateVerdict: string | null;
            /** Hitrate */
            hitRate: number | null;
            /** Horizon */
            horizon: string;
            /** Id */
            id: string;
            /** Liveclosed */
            liveClosed: number;
            /** Livereturn */
            liveReturn: number | null;
            /** Maxdd */
            maxDd: number | null;
            /** Name */
            name: string;
            /** Origin */
            origin: string;
            /** Sharpe */
            sharpe: number | null;
            /** Status */
            status: string;
            /** Statusreason */
            statusReason: string | null;
            /** Trades */
            trades: number;
            /** Winrate */
            winRate: number | null;
        };
        /** TradeOut */
        TradeOut: {
            /** Charges */
            charges: number;
            /** Delayed */
            delayed: boolean;
            /** Feedlags */
            feedLagS: number | null;
            /** Fill */
            fill: number;
            /** Fillbasis */
            fillBasis: string;
            /** Fillreason */
            fillReason: string;
            /** Id */
            id: number;
            /** Journalnote */
            journalNote: string | null;
            /** Orderid */
            orderId: number;
            /** Qty */
            qty: number;
            /** Realisedpnl */
            realisedPnl: number | null;
            /** Side */
            side: string;
            /** Symbol */
            symbol: string;
            /** Time */
            time: string;
        };
        /** TradeRow */
        TradeRow: {
            /** Date */
            date: string;
            /** Ret */
            ret: number;
            /** Symbol */
            symbol: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WalkForwardWindow */
        WalkForwardWindow: {
            /** Benchreturn */
            benchReturn: number | null;
            /** Label */
            label: string;
            /** Result */
            result: string;
            /** Stratreturn */
            stratReturn: number | null;
            /** Testend */
            testEnd: string;
            /** Teststart */
            testStart: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    briefs_api_briefs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefListItem"][];
                };
            };
        };
    };
    brief_api_briefs__day__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    new_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewOrder"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_orders_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_order_api_orders__oid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                oid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    picks_api_picks_get: {
        parameters: {
            query?: {
                date?: string | null;
                horizon?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pick"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolios_api_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"][];
                };
            };
        };
    };
    new_portfolio_api_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPortfolio"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_api_portfolios__pid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    stock_search_api_stocks_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_api_stocks__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bars_api_stocks__symbol__bars_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bar"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySummary"][];
                };
            };
        };
    };
    strategy_api_strategies__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_strategies__slug__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_api_strategies__slug__retire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    journal_api_trades__tid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
